# Generated by Django 5.2 on 2025-07-16 13:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="phone_number",
            field=models.CharField(
                blank=True,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?:\\+234|0)[789][01]\\d{8}$", "Enter a Valid Phone Number"
                    )
                ],
            ),
        ),
    ]
