# Generated by Django 5.2 on 2025-04-29 18:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_default=uuid.UUID("59842dfa-252b-11f0-8f2f-a0b3ccc6bc7f"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("product_name", models.CharField(max_length=100)),
                ("product_slug", models.SlugField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timpstamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
