# Generated by Django 5.2 on 2025-05-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_slug",
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
