# Generated by Django 5.2 on 2025-05-01 21:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price",
            field=models.FloatField(default=1000.0),
        ),
        migrations.AddField(
            model_name="product",
            name="product_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                db_default=uuid.UUID("182365df-26d2-11f0-bc62-a0b3ccc6bc7f"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
