# Generated by Django 5.2 on 2025-05-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_product_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="timpstamp",
            new_name="timepstamp",
        ),
    ]
