# Generated by Django 5.2 on 2025-05-23 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_rename_timepstamp_product_timestamp"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["product_name"], name="product_name_index"),
        ),
    ]
