# Generated by Django 5.2 on 2025-05-30 21:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_options_product_product_name_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "order_id",
                    models.UUIDField(
                        default=uuid.UUID("097ddad5-3d9b-11f0-ade8-a0b3ccc6bc7f"),
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Order ID",
                    ),
                ),
                (
                    "manifest",
                    models.TextField(blank=True, null=True, verbose_name="Manifest"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("default", "Default"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="Product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
