# Generated by Django 5.2 on 2025-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderProxy",
            fields=[],
            options={
                "verbose_name": "User Order",
                "verbose_name_plural": "User Orders",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.order",),
        ),
        migrations.AddField(
            model_name="order",
            name="number_of_items",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="quantities",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("default", "Default"),
                    ("delivered", "Delivered"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                ],
                default="default",
                max_length=20,
            ),
        ),
    ]
