# Generated by Django 5.2 on 2025-06-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0007_orderproxy_order_number_of_items_product_quantities_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="quantities",
            new_name="quantity",
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
