# Generated by Django 5.2 on 2025-07-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_rename_quantities_product_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="out_of_stock",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(quantity__lte=0, then=True),
                    default=False,
                    output_field=models.BooleanField(),
                ),
                output_field=models.BooleanField(),
            ),
        ),
    ]
