# Generated by Django 5.2 on 2025-08-17 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_comment_reply_comment_comments_message_45ef19_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ("-timestamp",)},
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("pending", "Pending"),
                    ("cancelled", "Cancelled"),
                    ("in_transit", "In Transit"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
