# Generated by Django 5.2 on 2025-08-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_alter_comment_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
