# Generated by Django 5.2 on 2025-09-19 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_alter_product_product_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-timestamp"],
                "permissions": (("user_product", "User Add/Update/Delete Product"),),
            },
        ),
    ]
