# Generated by Django 5.2 on 2025-09-20 21:01

import helpers.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_product_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_slug",
            field=helpers.fields.AutoSlugField(
                blank=True, null=True, perform_from="product_name"
            ),
        ),
    ]
