# Generated by Django 5.2 on 2025-10-09 19:27

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_order_inactive_at_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.GeneratedField(
                db_persist=False,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("product__price"), "*", models.F("product__quantity")
                ),
                output_field=models.IntegerField(),
            ),
        ),
    ]
