# Generated by Django 5.2 on 2025-10-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0015_order_inactive_at_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number_of_items",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
