# Generated by Django 5.2 on 2025-05-26 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="token",
            old_name="expired",
            new_name="expired_at",
        ),
    ]
