# Generated by Django 5.2 on 2025-09-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FeedBack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("user_id", models.CharField(default="", max_length=250)),
                ("complain", models.TextField()),
                (
                    "complain_type",
                    models.CharField(
                        choices=[("order", "Order"), ("other", "Other")],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("timestamp", models.DateField(auto_now=True)),
            ],
        ),
    ]
