# Generated by Django 5.2 on 2025-09-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="complain_type",
            field=models.CharField(
                choices=[("order", "Order"), ("other", "Other")],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user_id",
            field=models.CharField(default="", max_length=250),
        ),
    ]
