# Generated by Django 5.2 on 2025-09-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="user_id",
            field=models.CharField(default="", max_length=300),
        ),
    ]
