# Generated by Django 5.2 on 2025-10-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_alter_feedback_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="complain_type",
            field=models.CharField(
                choices=[("order", "Order"), ("site", "Site"), ("other", "Other")],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user_id",
            field=models.TextField(default=""),
        ),
        migrations.AddIndex(
            model_name="feedback",
            index=models.Index(fields=["user_id", "email"], name="user_idx"),
        ),
    ]
